### ISSUE TITLE
doesn't support database_path()

### ISSUE THREAD

**Issue by ZsgsDesign** [MilesChou/docusema#2]
Laravel Database Config supports Laravel Standard Helper Functions like `database_path()` and others, it looks like this package doesn't support those.

**Comment by MilesChou** [comment]
How can I perform this problem?

**Comment by ZsgsDesign** [comment]
Just use database_path() in the database config file, e.g.:
```php
        'sqlite' => [
            'driver' => 'sqlite',
            'database' => env('DB_DATABASE', database_path('database.sqlite')),
            'prefix' => '',
            'foreign_key_constraints' => env('DB_FOREIGN_KEYS', true),
        ],
```

I don't have any clue, run `app()` in the first place is one solution but it's really a waste.
Or we can simply catch the exceptions?

I am currently writing a separate config of this file to solve the problem.

**Comment by roc26002w** [comment]
I have same issue XDXD.

**Comment by MilesChou** [comment]
If you use Laravel Project, please use https://github.com/MilesChou/schemarkdown instead.
